# Generated by Django 3.1.5 on 2021-06-30 15:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.BooleanField()),
                ('create_at', models.DateTimeField(default=datetime.datetime(2021, 6, 30, 19, 59, 4, 41762))),
                ('update_at', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product.productcategory')),
            ],
        ),
    ]
